services:
  db:
    image: postgres:16-alpine
    environment:
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: sociacolhe
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
      - ./migrations:/docker-entrypoint-initdb.d
  api:
    build: .
    command: ["go", "run", "./cmd/server"]
    environment:
      PORT: "8080"
      DATABASE_URL: "postgres://postgres:postgres@db:5432/sociacolhe?sslmode=disable"
      JWT_SECRET: "dev-secret"
      ALLOW_SIGNUP: "true"
    depends_on:
      - db
    ports:
      - "8080:8080"
volumes:
  pgdata:
